os: linux
dist: focal
language: python

python:
  - "3.8"
  - "3.9"

services:
  - docker
before_install:
  # Use Docker rabbitmq instead of Travis'. Travis's doesn't use SSL.
  - docker pull rabbitmq:3.8.11-alpine
  - test-server/prepare-certs.sh  # Create SSL certificates used in tests
  - docker run --rm -d -p 5671:5671 -p 5672:5672 -v "/${TRAVIS_BUILD_DIR}"/test-server:/test-server -e RABBITMQ_SSL_CACERTFILE=/test-server/ca.cert -e RABBITMQ_SSL_CERTFILE=/test-server/server.cert -e RABBITMQ_SSL_KEYFILE=/test-server/server.key -e RABBITMQ_SSL_VERIFY=verify_peer -e RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=true -e RABBITMQ_CONFIG_FILE=/test-server/rabbitmq rabbitmq:3.8.11-management-alpine
  # Now it'll start up while we're doing our install. There's a race, but
  # it's likely rabbitmq will be up before pytest starts.
  - python -m pip install poetry tox-travis
install: poetry install -v
script: tox

jobs:
  include:
    - stage: deploy
      python: "3.9"
      before_install: python -m pip install poetry
      install: skip
      script: skip
      before_deploy:
        - poetry version $(git describe --tags --exact-match --match="v*.*.*" | cut -b2-)  # fallback "" means, "0.0.0"
        - poetry config pypi-token.pypi $PYPI_TOKEN
      deploy:
        skip_cleanup: true  # so "poetry version" stays
        provider: script
        script: poetry publish --build
        on:
          tags: true

env:
  global:
    - secure: "tJ/NF3ly0dmDBZmQkEA9zyjhEdEybfxODGk0S0+GkWm+KiLTcTirtw49l2irdqcfYCUQmj9x4Lr2RwcZsJwxbclpYTQHcvPEYpr7bMoFiTyANfGwpFu6JvAEUztXJ8RYzZUxjcnyL5dgZSsHrO3RUnw+imh7nTrESee7eYqMj14QeLjyvUOMfeCWu3G5KnRe1r+q9GvaC1vthHudlGfq+zD4w3AgRARECA+Xnx73xP28fOWP/f7ZzbXaD259bdD6uZGMo9Flq2xvkdHht5k+wbetjbbWfxU+Qd2V5RbBhYD/SyspzN9D38w9zHtOSskCdQFMO8V4ir4SziMI03e6dw9Bc8KS1YsiHFjqkThDPOJ3LreBfIMMiDz+OoQ7t3DRz7+Klh/cFw+BizeoVtOV9BhutXTm1zhJvFTKM5g3ZgCl3MwwCCz39kzmcqaop2yhIyWoauCxNy5sYMxzgrrfNtpl/j9xdSmZHl+fpuXdN51OEVHObkbJ8/TJnTugRNfH9wBd/JuEYG8zYd+jwml5H1BxPyH8NW0K1uo5IkjXACoFH6My3OnIM20I/H+dXE5E0kZetGwo6REv3uGwH63MR8SzRr+h3+g7ZBnsIUu6376A6rc7UbC4Y3KshzuFwuiAmBZpYeFIlVSLPMTyOuLdfJZuSzkdQAwJVe8abmI/Hgc=" # PYPI_TOKEN=...
